import { readFileSync } from 'node:fs';
import path from 'node:path';

import { defineConfig } from 'vitest/config';

const pkg = JSON.parse(readFileSync('./package.json', 'utf8')) as { version: string };

export default defineConfig({
  define: {
    __PKG_VERSION__: JSON.stringify(pkg.version),
  },
  test: {
    globals: true,
    root: '.',
    include: ['tests/**/*.test.ts'],
    // Windows runners are noticeably slower than Linux/macOS — bump the
    // default 5s test timeout and 10s hook timeout so e2e cases that build
    // the CLI or chunk a small corpus don't fail spuriously.
    testTimeout: process.platform === 'win32' ? 30_000 : 10_000,
    hookTimeout: process.platform === 'win32' ? 60_000 : 30_000,
    // On Windows, exclude test suites that depend on a POSIX bash on PATH.
    // These exercise the runtime/**/scripts/*.sh helpers; the shipped product
    // never invokes them on Windows. Tracked for proper Windows bash support
    // (e.g. detecting Git Bash) in a follow-up.
    exclude:
      process.platform === 'win32'
        ? [
            '**/node_modules/**',
            '**/dist/**',
            'tests/unit/skills/**',
            'tests/unit/scripts/**',
            'tests/unit/hooks/silent-update.test.ts',
          ]
        : ['**/node_modules/**', '**/dist/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov', 'json-summary'],
      include: ['src/**/*.ts'],
      excludeAfterRemap: true,
      exclude: [
        'src/**/*.d.ts',
        'src/adapters/adapter.interface.ts',
        'src/cache/types.ts',
        'src/context/types.ts',
        'src/context/inference-provider.ts',
        'src/core/types/design-tokens.ts',
        'src/core/types/document-generation.ts',
        'src/core/types/feature-spec.ts',
        'src/core/types/introspection.ts',
        'src/core/types/logger.ts',
        'src/core/types/onboarding.ts',
        'src/core/types/post-classification.ts',
        'src/core/types/pack.ts',
        'src/core/types/pre-classification.ts',
        'src/core/types/repository.ts',
        'src/core/types/template.ts',
        'src/introspection/ecosystems/types.ts',
        'src/patterns/types.ts',
        'src/compliance/types.ts',
        'src/compliance/spec-review-detectors/missing-negative-detector.ts',
        '**/spec-review-detectors/missing-negative-detector.ts',
        'src/pipeline/phases/phase.interface.ts',
        'src/session/types.ts',
        'src/verification/gates/gate.interface.ts',
        'src/workflows/types.ts',
        'src/cli/commands/refresh.ts',
        'src/context/ast-chunker.ts',
        'src/context/budget-optimizer.ts',
        'src/context/chunk-index.ts',
        'src/context/hit-tracker.ts',
        'src/context/relevance-scorer.ts',
        'src/context/reranker.ts',
        'src/core/project-intelligence.ts',
        'src/core/project-profile.ts',
        'src/core/stack-profile.ts',
        'src/design-tokens/service.ts',
        'src/detection/detector.ts',
        'src/detection/signals/react.ts',
        'src/detection/signals/short-video.ts',
        'src/detection/signals/vue.ts',
        'src/document/progress-tracker.ts',
        'src/document/workflow.ts',
        'src/health/checker.ts',
        'src/introspection/cache.ts',
        'src/introspection/ecosystems/node-npm.ts',
        'src/introspection/ecosystems/php.ts',
        'src/introspection/ecosystems/python.ts',
        'src/introspection/ecosystems/registry.ts',
        'src/introspection/environment-traits.ts',
        'src/introspection/parsers/composer.ts',
        'src/introspection/parsers/dart.ts',
        'src/introspection/parsers/npm.ts',
        'src/introspection/parsers/pnpm.ts',
        'src/introspection/stack-introspector.ts',
        'src/mcp/server-registry.ts',
        'src/onboarding/orchestrator.ts',
        'src/onboarding/prompts.ts',
        'src/onboarding/rag-onboarding.ts',
        'src/onboarding/rule-generator.ts',
        'src/packs/loader.ts',
        'src/packs/manager.ts',
        'src/patterns/pattern-rag.ts',
        'src/patterns/pattern-recorder.ts',
        'src/patterns/pattern-suggester.ts',
        'src/pentest/file-check-mapper.ts',
        'src/pentest/findings.ts',
        'src/pentest/incremental-scanner.ts',
        'src/pentest/osv.ts',
        'src/pentest/progress-tracker.ts',
        'src/pentest/report-builder.ts',
        'src/pentest/shared.ts',
        'src/pipeline/feature-development-policy.ts',
        'src/pipeline/lane-runner.ts',
        'src/pipeline/phases/pentest-retest.ts',
        'src/pipeline/phases/pentest.ts',
        'src/pipeline/phases/root-cause-analysis.ts',
        'src/pipeline/phases/verification.ts',
        'src/pipeline/router.ts',
        'src/pipeline/stream-truncator.ts',
        'src/pipeline/workflow-router.ts',
        'src/planning/index.ts',
        'src/planning/manifest-types.ts',
        'src/rag/audit.ts',
        'src/rag/benchmark-gates.ts',
        'src/rag/providers.ts',
        'src/rag/secrets.ts',
        'src/rag/vector-index.ts',
        'src/repository/discovery.ts',
        'src/resolver/deduplicator.ts',
        'src/resolver/inheritance.ts',
        'src/resolver/resolver.ts',
        'src/session/handoff-writer.ts',
        'src/skills/frontmatter-parser.ts',
        'src/stack-docs/generator.ts',
        'src/templates/context-builders/runner-scripts.ts',
        'src/templates/engine.ts',
        'src/update/audit.ts',
        'src/update/updater.ts',
        'src/validators/validator.ts',
        'src/verification/gates/documentation-freshness.ts',
        'src/workflows/engine.ts',
        'src/workflows/parallel-executor.ts',
        'src/workflows/pentest-retest.ts',
        'src/workflows/pentest.ts',
        'src/workflows/root-cause-analysis.ts',
        'src/workflows/step-executor.ts',
        'src/workflows/template-loader.ts',
        'src/workflows/template-validator.ts',
      ],
      thresholds: {
        branches: 95,
        functions: 95,
        lines: 95,
        statements: 95,
        // The stages workflow is the delivery-critical spine (issue #307): the
        // block-forward gate, marker parse, live writer and narration must never
        // regress unseen, so stage-evidence holds a 100% floor, not the repo's 95%.
        'src/stage-evidence/**': {
          branches: 100,
          functions: 100,
          lines: 100,
          statements: 100,
        },
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
