import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

import { PATHS } from '@/core/constants/paths.js';
import {
  DesignTokenService,
  DesignTokensMissingError,
  DesignTokensPlaceholderError,
} from '@/design-tokens';

describe('DesignTokenService', () => {
  let root: string;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'paqad-design-tokens-'));
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  // Write a real, user-authored tokens file (no placeholder `$comment`).
  function writeRealTokens(): void {
    const target = join(root, PATHS.DESIGN_TOKENS_FILE);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(
      target,
      JSON.stringify(
        {
          color: {
            primary: { $value: '#123456', $type: 'color', $description: 'Brand primary.' },
          },
          spacing: {
            md: { $value: '1rem', $type: 'dimension' },
          },
        },
        null,
        2,
      ),
    );
  }

  it('seeds a placeholder scaffold rather than a generic brand', async () => {
    const service = new DesignTokenService();
    await service.seed(root);

    const tokensJson = readFileSync(join(root, PATHS.DESIGN_TOKENS_FILE), 'utf8');
    // The file self-identifies as an unedited placeholder…
    expect(tokensJson).toContain('$comment');
    expect(tokensJson).toContain('PLACEHOLDER design tokens seeded by paqad-ai');
    // …and ships no invented brand values.
    expect(tokensJson).not.toContain('#0F766E');
    expect(tokensJson).not.toContain('Satoshi');
    expect(PATHS.DESIGN_TOKENS_FILE).toBe('docs/instructions/design-system/design-tokens.json');
  });

  it('refuses to generate docs or theme exports while the file is the placeholder', async () => {
    const service = new DesignTokenService();
    await service.seed(root);

    await expect(service.generateDocs(root)).rejects.toBeInstanceOf(DesignTokensPlaceholderError);
    await expect(service.exportTheme(root, 'laravel')).rejects.toBeInstanceOf(
      DesignTokensPlaceholderError,
    );
  });

  it('generates derived docs and theme exports from real, user-authored tokens', async () => {
    const service = new DesignTokenService();
    writeRealTokens();

    await service.writeDocs(root);
    await service.writeThemeExports(root, 'laravel');

    const tokensMd = readFileSync(join(root, PATHS.DESIGN_SYSTEM_DIR, 'tokens.md'), 'utf8');
    expect(tokensMd).toContain('Design Tokens');
    // Generated docs carry a do-not-edit banner pointing back at the source.
    expect(tokensMd).toContain('GENERATED by paqad-ai');
    expect(tokensMd).toContain(PATHS.DESIGN_TOKENS_FILE);
    expect(readFileSync(join(root, '.paqad/theme/theme.css'), 'utf8')).toContain('--color-primary');
    const tailwindTheme = readFileSync(join(root, '.paqad/theme/tailwind.theme.cjs'), 'utf8');
    expect(tailwindTheme).toContain("'color-primary' : '#123456'");
  });

  it('throws DesignTokensMissingError when the tokens file is absent', async () => {
    const service = new DesignTokenService();
    await expect(service.load(root)).rejects.toBeInstanceOf(DesignTokensMissingError);
  });
});
