// Reuse-catalog generator (issue #353). Turns the code-knowledge index into
// docs/instructions/registries/reuse-catalog.md: per module, the exported symbols
// most worth reusing (highest caller count first), so the next change can call an
// existing helper instead of writing a new one. Regenerated by `paqad-ai index
// build` and marked generated — never hand-edited.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { PATHS } from '@/core/constants/paths.js';

import type { CodeKnowledgeIndex, CodeKnowledgeSymbol } from './types.js';

/** Symbols listed per module, highest caller count first. */
export const REUSE_CATALOG_TOP_N = 15;

const GENERATED_HEADER =
  '<!-- Generated by `paqad-ai index build` (issue #353). Do not edit by hand. -->';

/** Table cells must not contain a raw `|` (it would split the column) or newlines. */
function cell(text: string): string {
  return text.replace(/\|/g, '/').replace(/\s+/g, ' ').trim();
}

function moduleHeading(slug: string | null): string {
  return slug ?? '(unattributed)';
}

function tableFor(symbols: CodeKnowledgeSymbol[]): string {
  const rows = symbols
    .slice()
    .sort((a, b) => b.caller_count - a.caller_count || a.name.localeCompare(b.name))
    .slice(0, REUSE_CATALOG_TOP_N)
    .map(
      (symbol) =>
        `| ${cell(symbol.name)} | \`${cell(symbol.signature)}\` | ${cell(symbol.file)} | ${symbol.caller_count} |`,
    );
  return ['| Symbol | Signature | File | Callers |', '| --- | --- | --- | --- |', ...rows].join(
    '\n',
  );
}

/** Render the reuse catalog markdown from an index. */
export function generateReuseCatalog(index: CodeKnowledgeIndex): string {
  const bySlug = new Map<string, CodeKnowledgeSymbol[]>();
  for (const symbol of index.symbols) {
    const key = moduleHeading(symbol.module_slug);
    const list = bySlug.get(key) ?? [];
    list.push(symbol);
    bySlug.set(key, list);
  }

  const sections = [...bySlug.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([slug, symbols]) => `## ${slug}\n\n${tableFor(symbols)}`);

  const intro =
    'Exported symbols across the codebase, most-reused first per module. Consult this ' +
    'before adding a new helper — the surface you need may already exist.';

  return [GENERATED_HEADER, '', '# Reuse Catalog', '', intro, '', ...sections, ''].join('\n');
}

/** Write the reuse catalog to docs/instructions/registries/reuse-catalog.md. */
export function writeReuseCatalog(projectRoot: string, index: CodeKnowledgeIndex): string {
  const target = join(projectRoot, PATHS.REGISTRIES_DIR, 'reuse-catalog.md');
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, generateReuseCatalog(index), 'utf8');
  return target;
}
