export const PATHS = {
  AGENCY_DIR: '.paqad',
  AGENCY_CACHE_DIR: '.paqad/cache',
  AGENCY_SESSION_DIR: '.paqad/session',
  PROJECT_PROFILE: '.paqad/project-profile.yaml',
  DETECTION_REPORT: '.paqad/detection-report.json',
  ONBOARDING_MANIFEST: '.paqad/onboarding-manifest.json',
  RAG_IGNORE_CONFIG: '.paqad/rag.ignore.yaml',
  STACK_DRIFT: '.paqad/stack-drift.json',
  STACK_SNAPSHOT: '.paqad/stack-snapshot.json',
  FRAMEWORK_VERSION: '.paqad/framework-version.txt',
  FRAMEWORK_PATH: '.paqad/framework-path.txt',
  GLOSSARY: '.paqad/glossary.md',
  HANDOFF: '.paqad/session/handoff.md',
  CHANGED_FILES: '.paqad/session/changed-files.json',
  ACTIVE_IMPLEMENTATION_SESSION: '.paqad/session/active-implementation.json',
  CONTEXT_HIT_LOG: '.paqad/session/context-hit-log.json',
  PROJECT_QUESTION_ANSWER: '.paqad/session/project-question-answer.json',
  AUDIT_LOG: '.paqad/audit.log',
  DECISIONS_DIR: '.paqad/decisions',
  DECISIONS_PENDING_DIR: '.paqad/decisions/pending',
  DECISIONS_RESOLVED_DIR: '.paqad/decisions/resolved',
  DECISIONS_EXPIRED_DIR: '.paqad/decisions/expired',
  DECISIONS_INDEX: '.paqad/decisions/index.json',
  DECISIONS_AUDIT_LOG: '.paqad/decisions/audit.jsonl',
  DECISIONS_LOCK: '.paqad/decisions/.lock',
  DECISION_PAUSE_CONTRACT: '.paqad/decision-pause-contract.md',
  // Feature 1 - Semantic Context Loader
  CHUNK_INDEX: '.paqad/context/chunk-index.json',
  LOAD_STATS: '.paqad/context/load-stats.json',
  VECTORS_DIR: '.paqad/vectors',
  VECTOR_INDEX: '.paqad/vectors/index.json',
  VECTOR_META: '.paqad/vectors/meta.json',
  SECRETS_ENV: '.paqad/secrets.env',
  GLOBAL_PATTERN_VECTORS_DIR: '.paqad/patterns/vectors',
  GLOBAL_PATTERN_VECTOR_INDEX: '.paqad/patterns/vectors/index.json',
  GLOBAL_PATTERN_VECTOR_META: '.paqad/patterns/vectors/meta.json',
  // Feature 2 - Predictive Cache
  TRANSITION_LOG: '.paqad/cache/transition-log.json',
  CACHE_METRICS: '.paqad/cache/metrics.json',
  PLANNING_SPECS_DIR: '.paqad/specs',
  // Issue #103 - persisted regression guards (one sidecar per defect_id)
  REGRESSION_GUARDS_DIR: '.paqad/regression-guards',
  // Issue #106 - flaky-test registry / quarantine list
  FLAKY_TESTS_DIR: '.paqad/flaky-tests',
  FLAKY_REGISTRY: '.paqad/flaky-tests/registry.json',
  // Issue #107 - per-run finding triage ledger (four-pile sort + reasons)
  FINDINGS_DIR: '.paqad/findings',
  TRIAGE_LEDGER: '.paqad/findings/triage.json',
  // Issue #109 - bidirectional traceability map (promise ↔ code ↔ test),
  // rebuilt from reality each run.
  TRACEABILITY_DIR: '.paqad/traceability',
  TRACEABILITY_MAP: '.paqad/traceability/map.json',
  PLANNING_MODULE_HEALTH_DIR: '.paqad/module-health',
  MODULE_HEALTH_EVIDENCE_DIR: '.paqad/module-health-evidence',
  MODULE_HEALTH_CONSUMED_EVENTS: '.paqad/module-health-consumed-events.json',
  MODULE_HEALTH_LOCK: '.paqad/locks/module-health.lock',
  MODULE_HEALTH_LOG: '.paqad/logs/module-health.log',
  COMPILED_RULES: '.paqad/compiled-rules.json',
  PLANNING_COSTS: '.paqad/cache/planning-costs.json',
  // Feature 3 - Context Budget Optimizer
  CONTEXT_BUDGET_STATE: '.paqad/session/context-budget.json',
  CONTEXT_SAVINGS: '.paqad/session/context-savings.json',
  // QW-1 - Deduplication
  DEDUP_STATS: '.paqad/session/dedup-stats.json',
  // Feature 6 - Handoff Compression
  HANDOFF_JSON: '.paqad/session/handoff.json',
  HANDOFF_STATS: '.paqad/session/handoff-stats.json',
  // Feature 7 - Workflow Engine
  WORKFLOWS_DIR: 'docs/instructions/workflows',
  WORKFLOW_RUNS_DIR: '.paqad/workflows',
  SKILL_CACHE_DIR: '.paqad/cache/skill-results',
  SKILL_INDEX: '.paqad/skill-index.json',
  DOC_PROGRESS: '.paqad/doc-progress.json',
  DOC_RUN_SESSION: '.paqad/session/doc-run.json',
  PENTEST_ROOT_DIR: '.paqad/pentest',
  PENTEST_RUNS_DIR: '.paqad/pentest/runs',
  INDEXES_DIR: '.paqad/indexes',
  DOCS_DIR: 'docs',
  FRAMEWORK_DOCS_DIR: 'docs/framework',
  FRAMEWORK_STACK_DIR: 'docs/instructions/stack',
  RCA_DIR: 'docs/rca',
  PENTEST_DIR: 'docs/pentest',
  PENTEST_RETEST_DIR: 'docs/pentest/retests',
  RULES_DIR: 'docs/instructions/rules',
  MODULE_MAP: 'docs/instructions/rules/module-map.yml',
  TOOLS_DIR: 'docs/instructions/tools',
  INSTRUCTIONS_DIR: 'docs/instructions',
  ARCHITECTURE_DIR: 'docs/instructions/architecture',
  DESIGN_SYSTEM_DIR: 'docs/instructions/design-system',
  // Canonical, hand-edited source of truth for the design system. Co-located
  // with the Markdown it generates so source and outputs share one folder.
  DESIGN_TOKENS_FILE: 'docs/instructions/design-system/design-tokens.json',
  MODULES_DIR: 'docs/modules',
  REGISTRIES_DIR: 'docs/instructions/registries',
  BENCHMARKS_DIR: 'docs/instructions/benchmarks',
  TECH_DEBT_DIR: 'docs/instructions/tech-debt',
  MODULE_DB_DIR: 'database',
  MODULE_API_DIR: 'api',
  MODULE_INTEGRATION_DIR: 'integration',
  MODULE_UI_DIR: 'ui',
  MODULE_FEATURES_DIR: 'features',
  MODULE_USER_FLOWS_DIR: 'user-flows',
  MODULE_RESEARCH_DIR: 'research',
  MODULE_DECISIONS_DIR: 'decisions',
  MODULE_ERROR_CATALOG: 'error-catalog.md',
  CLAUDE_MD: 'CLAUDE.md',
  AGENTS_MD: 'AGENTS.md',
  ANTIGRAVITY_MD: 'ANTIGRAVITY.md',
  GEMINI_MD: 'GEMINI.md',
  SCRIPTS_DIR: 'scripts',
  HOOKS_DIR: '.paqad/hooks',
  LOGS_DIR: '.paqad/logs',
  LOCKS_DIR: '.paqad/locks',
  AUTO_UPDATE_LOG: '.paqad/logs/auto-update.log',
  HOOKS_SILENT_UPDATE: '.paqad/hooks/silent-update.sh',
  // Issue #80 — living module lifecycle
  PROSPECTIVE_DECISIONS_DIR: '.paqad/decisions/module-decisions',
  MODULE_MAP_HISTORY_DIR: '.paqad/module-map/history',
  MODULE_MAP_EVENTS_LOG: '.paqad/module-map/events.jsonl',
  MODULE_MAP_DRIFT: '.paqad/module-map/drift.json',
  // Issue #89 — rules-as-scripts
  RULE_SCRIPT_MAP: 'docs/instructions/rules/rule-script-map.yml',
  RULE_SCRIPTS_DIR: '.paqad/scripts/rules',
  RULE_SCRIPTS_CACHE_DIR: '.paqad/scripts/rules/.cache',
  RULE_SCRIPTS_REPORT: '.paqad/scripts/rules/.cache/report.json',
  RULE_SCRIPTS_DRIFT: '.paqad/scripts/rules/.cache/drift.json',
  RULE_SCRIPT_MAP_HISTORY_DIR: '.paqad/scripts/rules/.history',
  RULE_SCRIPT_MAP_EVENTS_LOG: '.paqad/scripts/rules/.history/events.jsonl',
} as const;

export const REGISTRIES = [
  'module-registry.md',
  'feature-registry.md',
  'model-registry.md',
  'api-registry.md',
  'job-event-registry.md',
  'component-registry.md',
  'screen-registry.md',
  'table-registry.md',
  'query-registry.md',
  'test-registry.md',
  'error-code-registry.md',
  'integration-registry.md',
  'reuse-catalog.md',
] as const;
