import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { ADAPTER_TYPES } from '@/core/types/adapter.js';
import { PATHS } from '@/core/constants/paths.js';
import { DECISION_CATEGORIES } from '@/planning/decision-packet.js';
import { DECISION_PAUSE_UI_NOTES } from '@/adapters/shared/decision-pause-ui-shim.js';

export const MANAGED_HEADER =
  '<!-- managed by paqad-ai — do not edit; regenerated by `paqad refresh --providers` -->';

/**
 * Builds the canonical Decision Pause Contract markdown that lives at
 * `.paqad/decision-pause-contract.md`. Sources the category list from
 * `DECISION_CATEGORIES` and the per-adapter UI notes from the shim so the
 * doc cannot drift from the runtime.
 */
export function buildDecisionPauseContractDocument(): string {
  const categoriesList = DECISION_CATEGORIES.map((category) => `- \`${category}\``).join('\n');
  const adapterRows = ADAPTER_TYPES.map(
    (adapter) => `| \`${adapter}\` | ${DECISION_PAUSE_UI_NOTES[adapter]} |`,
  ).join('\n');

  return `${MANAGED_HEADER}

# Decision Pause Contract

Before implementing any choice that falls into one of the categories below, write a Decision Packet to \`.paqad/decisions/pending/D-{id}.json\` and stop work. Do not continue until \`.paqad/decisions/resolved/D-{id}.json\` exists. \`{id}\` is an opaque, time-sortable id the decision store allocates for you — do not hand-compute a sequential number; call the store to mint one.

## Categories

${categoriesList}

## Resolution flow

1. Write the packet to \`.paqad/decisions/pending/D-{id}.json\` (the store allocates \`{id}\`).
2. Present the packet's options to the user via the host's interactive UI (see the per-adapter table below). If multiple packets are pending, ask them one at a time in creation order (ids sort chronologically). If a packet has more than 4 options, present the top 4 — the user can pick "Other" to write in an alternative.
3. When the user answers, move the file from \`.paqad/decisions/pending/D-{id}.json\` to \`.paqad/decisions/resolved/D-{id}.json\`, adding these fields to the JSON: \`chosen\` (the selected option_key), \`rationale\` (any free-text note the user added), and \`resolved_at\` (ISO 8601 timestamp).
4. Only after the resolved file exists may implementation continue.

## Per-adapter UI

| Adapter | UI primitive |
| --- | --- |
${adapterRows}

## Fallback

If the interactive UI is not available (non-interactive run, hook context, etc.), stop work and wait until \`.paqad/decisions/resolved/D-{id}.json\` exists — created out of band by the user.
`;
}

/**
 * Writes a markdown file, but only if the content has actually changed.
 * Re-onboarding produces a byte-identical file (and mtime is preserved by the
 * filesystem) when nothing meaningful changed.
 */
export function writeMarkdownIfChanged(path: string, content: string): boolean {
  // Single read, catch ENOENT — avoids the existsSync/readFileSync TOCTOU
  // race that CodeQL's "Potential file system race condition" check flags.
  let existing: string | null = null;
  try {
    existing = readFileSync(path, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
  if (existing === content) {
    return false;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  return true;
}

/**
 * Writes the canonical contract to `<projectRoot>/.paqad/decision-pause-contract.md`.
 * Returns true if the file was written/updated, false if it was already up to date.
 */
export function writeDecisionPauseContractDocument(projectRoot: string): boolean {
  const path = join(projectRoot, PATHS.DECISION_PAUSE_CONTRACT);
  return writeMarkdownIfChanged(path, buildDecisionPauseContractDocument());
}
