import { ADAPTER_TYPES } from '@/core/types/adapter.js';
import { DECISION_CATEGORIES } from '@/planning/decision-packet.js';
import { DECISION_PAUSE_UI_NOTES } from '@/adapters/shared/decision-pause-ui-shim.js';

export const MANAGED_HEADER =
  '<!-- managed by paqad-ai — do not edit; regenerated by `paqad refresh --providers` -->';

/**
 * Builds the canonical Decision Pause Contract BODY (without the managed header).
 * Sources the category list from `DECISION_CATEGORIES` and the per-adapter UI
 * notes from the shim so the contract cannot drift from the runtime.
 *
 * This body is the single source of truth for the contract: the framework
 * bootstrap (`runtime/AGENT-BOOTSTRAP.md`, assembled by
 * `src/onboarding/agent-bootstrap-writer.ts`) inlines it — including the
 * per-adapter UI table whose `claude-code` row is the instruction that keeps the
 * Claude Code decision "tray" (`AskUserQuestion`) firing. The contract ships
 * inside the framework install and is loaded from there; it is no longer copied
 * into every project's `.paqad/` (issue #229).
 */
export function buildDecisionPauseContractBody(): string {
  const categoriesList = DECISION_CATEGORIES.map((category) => `- \`${category}\``).join('\n');
  const adapterRows = ADAPTER_TYPES.map(
    (adapter) => `| \`${adapter}\` | ${DECISION_PAUSE_UI_NOTES[adapter]} |`,
  ).join('\n');

  return `# Decision Pause Contract

Before implementing any choice that falls into one of the categories below, write a Decision Packet to \`.paqad/decisions/pending/D-{id}.json\` and stop work. Do not continue until \`.paqad/decisions/resolved/D-{id}.json\` exists. \`{id}\` is an opaque, time-sortable id the decision store allocates for you — do not hand-compute a sequential number; call the store to mint one.

## Categories

${categoriesList}

## Resolution flow

1. Write the packet to \`.paqad/decisions/pending/D-{id}.json\` (the store allocates \`{id}\`).
2. Present the packet's options to the user via the host's interactive UI (see the per-adapter table below). If multiple packets are pending, ask them one at a time in creation order (ids sort chronologically). If a packet has more than 4 options, present the top 4 — the user can pick "Other" to write in an alternative.
3. When the user answers, move the file from \`.paqad/decisions/pending/D-{id}.json\` to \`.paqad/decisions/resolved/D-{id}.json\`, adding these fields to the JSON: \`chosen\` (the selected option_key), \`rationale\` (any free-text note the user added), and \`resolved_at\` (ISO 8601 timestamp).
4. Only after the resolved file exists may implementation continue.

## Per-adapter UI

Use the row that matches the \`Adapter:\` value in the entry file that pointed you to this bootstrap.

| Adapter | UI primitive |
| --- | --- |
${adapterRows}

## Fallback

If the interactive UI is not available (non-interactive run, hook context, etc.), stop work and wait until \`.paqad/decisions/resolved/D-{id}.json\` exists — created out of band by the user.`;
}

/**
 * The Decision Pause Contract as a standalone managed document (header + body).
 * Kept for callers/tests that want the document form; the project-level
 * `.paqad/` copy is no longer written (issue #229).
 */
export function buildDecisionPauseContractDocument(): string {
  return `${MANAGED_HEADER}\n\n${buildDecisionPauseContractBody()}\n`;
}
