import { PATHS } from '@/core/constants/paths.js';

import type { DashboardSectionId, SectionData } from '../types.js';
import { collectDocsArea, type DocsAreaSpec } from './docs-area.js';

interface AreaSpec extends Omit<DocsAreaSpec, 'fileFilter'> {
  fileFilter?: DocsAreaSpec['fileFilter'];
}

const REGISTRIES_DIR = 'docs/instructions/registries';
const TECH_DEBT_DIR = 'docs/instructions/tech-debt';

const AREA_SPECS: ReadonlyArray<AreaSpec> = [
  {
    id: 'design-system',
    title: 'Design system',
    relPath: PATHS.DESIGN_SYSTEM_DIR,
    expectedMin: 1,
    helper: {
      what: 'docs/instructions/design-system/ holds tokens, components, and patterns. Every UI change is checked against these.',
      goodLooksLike: 'tokens.md, components.md, and patterns.md present and kept in sync with the codebase.',
    },
    missingCommand: '`paqad refresh --design-system`',
  },
  {
    id: 'stack',
    title: 'Stack',
    relPath: PATHS.FRAMEWORK_STACK_DIR,
    expectedMin: 2,
    helper: {
      what: 'docs/instructions/stack/ documents the resolved framework, traits, and version bands the project runs on.',
      goodLooksLike: 'overview.md and versions.md present, regenerated after every dependency change.',
    },
    missingCommand: '`create documentation`',
  },
  {
    id: 'registries',
    title: 'Registries',
    relPath: REGISTRIES_DIR,
    expectedMin: 2,
    helper: {
      what: 'docs/instructions/registries/ holds the canonical lookup pages (commands.md, modules.md) other docs reference.',
      goodLooksLike: 'commands.md and modules.md generated by the docs workflow and refreshed when the project changes.',
    },
    missingCommand: '`create documentation`',
  },
  {
    id: 'tools',
    title: 'Tools',
    relPath: PATHS.TOOLS_DIR,
    expectedMin: 1,
    helper: {
      what: 'docs/instructions/tools/ lists per-stack tool integrations (e.g. React docs, MCP entries).',
      goodLooksLike: 'At least one tool reference for each active stack.',
    },
    missingCommand: '`paqad-ai refresh`',
  },
  {
    id: 'tech-debt',
    title: 'Tech debt',
    relPath: TECH_DEBT_DIR,
    expectedMin: 1,
    helper: {
      what: 'docs/instructions/tech-debt/ tracks known shortcuts, TODOs, and deferred work the framework is aware of.',
      goodLooksLike: 'A tech-debt overview present and refreshed as items are added or closed out.',
    },
    missingCommand: '`create documentation`',
  },
];

export function collectInstructionsAreas(projectRoot: string, now: number = Date.now()): SectionData[] {
  return AREA_SPECS.map((spec) =>
    collectDocsArea(
      projectRoot,
      {
        id: spec.id,
        title: spec.title,
        relPath: spec.relPath,
        expectedMin: spec.expectedMin,
        helper: spec.helper,
        missingCommand: spec.missingCommand,
      },
      now,
    ),
  );
}

export const INSTRUCTIONS_AREA_IDS: ReadonlyArray<DashboardSectionId> = AREA_SPECS.map((s) => s.id);
