import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import YAML from 'yaml';

import { PATHS } from '@/core/constants/paths.js';

import { ageInDays, bandForScore, scoreFreshness } from '../scoring/index.js';
import type { SectionData } from '../types.js';
import { fileMtime } from './fs-helpers.js';

interface ModuleMapModule {
  slug?: unknown;
  name?: unknown;
}

interface ModuleMap {
  modules?: unknown;
}

const HELPER = {
  what: 'docs/modules/<slug>/index/summary.md is the canonical per-module documentation generated by `create module documentation` (Stage 2 of the docs workflow).',
  goodLooksLike: 'Every module in module-map.yml has an index/summary.md, all fresh within the last 30 days.',
} as const;

function readModuleSlugs(projectRoot: string): string[] {
  const path = join(projectRoot, PATHS.MODULE_MAP);
  if (!existsSync(path)) return [];
  try {
    const map = YAML.parse(readFileSync(path, 'utf8')) as ModuleMap | null;
    const modules = Array.isArray(map?.modules) ? (map.modules as ModuleMapModule[]) : [];
    return modules
      .map((m) => (typeof m.slug === 'string' ? m.slug : null))
      .filter((s): s is string => s !== null);
  } catch {
    return [];
  }
}

export function collectModuleDocs(projectRoot: string, now: number = Date.now()): SectionData {
  const slugs = readModuleSlugs(projectRoot);
  if (slugs.length === 0) {
    return {
      id: 'module-docs',
      title: 'Module docs',
      band: 'unknown',
      score: null,
      summary: 'No module-map.yml — run `create documentation`.',
      metrics: [],
      helper: HELPER,
    };
  }

  let present = 0;
  let staleCount = 0;
  let oldestAgeDays: number | null = null;

  for (const slug of slugs) {
    const summaryPath = join(projectRoot, PATHS.MODULES_DIR, slug, 'index', 'summary.md');
    const mtime = fileMtime(summaryPath);
    if (mtime === null) continue;
    present += 1;
    const freshness = scoreFreshness(mtime, { now });
    if (freshness < 100) staleCount += 1;
    const age = ageInDays(mtime, now);
    if (age !== null && (oldestAgeDays === null || age > oldestAgeDays)) {
      oldestAgeDays = age;
    }
  }

  const presenceRatio = present / slugs.length;
  const freshRatio = present > 0 ? (present - staleCount) / present : 0;
  const score = Math.round(presenceRatio * 60 + freshRatio * 40);

  const missing = slugs.length - present;
  const summary =
    missing === 0
      ? `${slugs.length} module(s) · ${staleCount} stale`
      : `${missing} of ${slugs.length} module(s) missing docs`;

  return {
    id: 'module-docs',
    title: 'Module docs',
    band: bandForScore(score),
    score,
    summary,
    metrics: [
      { label: 'modules', value: `${present}/${slugs.length}` },
      { label: 'stale', value: String(staleCount) },
      { label: 'oldest', value: oldestAgeDays !== null ? `${oldestAgeDays}d` : '—' },
    ],
    helper: HELPER,
    details: {
      moduleCount: slugs.length,
      present,
      missing: slugs.filter((s) => !existsSync(join(projectRoot, PATHS.MODULES_DIR, s, 'index', 'summary.md'))),
    },
  };
}
