// Analytics tracking-map registry (issue #241 §8). The overall picture "what is tagged to
// what" as a human-readable registry alongside modules.md / commands.md. It is a PROJECTION
// of the `paqad.analytics-tag` ledger, not a hand-drifted document: the table is generated
// by folding the rows, so the map and the ledger can never disagree. The one hand-authored
// part is the convention preamble (naming rules, provider policy) — a decision, not an
// observation — which reconcile preserves verbatim between its markers.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { readAllSessionRows } from '@/session-ledger/ledger.js';

import { foldAnalyticsTagRows } from './fold.js';
import { ANALYTICS_TAG_DOC_TYPE } from './types.js';

/** Repo-relative path to the generated registry. */
export const ANALYTICS_MAP_PATH = 'docs/instructions/registries/analytics-tracking-map.md';

const PREAMBLE_START = '<!-- paqad:analytics-map:preamble:start -->';
const PREAMBLE_END = '<!-- paqad:analytics-map:preamble:end -->';
const TABLE_START = '<!-- paqad:analytics-map:table:start -->';
const TABLE_END = '<!-- paqad:analytics-map:table:end -->';

const DEFAULT_PREAMBLE = `## How analytics is used here

_Hand-authored. Describe the naming convention (e.g. \`snake_case\`, \`verb_object\`), the
providers in play, and anything a new contributor needs before adding a tag. Everything
below the table markers is generated from the ledger — edit this preamble, not the table._`;

const HEADER = `# Analytics Tracking Map

> **Generated — do not hand-edit the table.** The table below is a projection of the
> \`paqad.analytics-tag\` ledger, regenerated by \`paqad-ai analytics map\` (and on
> every tag write). Only the convention preamble between its markers is hand-owned; reconcile
> preserves it. See issue #241.`;

/** Escape a cell so a stray backslash, pipe, or newline can't break the markdown table
 *  (surface-doc rule). Backslash is escaped FIRST so an existing `\` is not conflated with
 *  the escape we add for pipes. */
function cell(value: string | null | undefined): string {
  return (value ?? '').replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/** Render the generated table from folded rows. */
export function renderAnalyticsMapTable(projectRoot: string): string {
  const rows = readAllSessionRows(projectRoot, ANALYTICS_TAG_DOC_TYPE);
  const fold = foldAnalyticsTagRows('all', rows);
  const head = '| event | provider | call site | occurrences | last seen |';
  const rule = '| --- | --- | --- | --- | --- |';
  if (fold.tags.length === 0) {
    return [head, rule, '| _(no tags recorded yet)_ | | | | |'].join('\n');
  }
  const body = fold.tags.map(
    (t) =>
      `| ${cell(t.tag_name)} | ${cell(t.tag_provider)} | ${cell(t.source_path)} | ${t.occurrences} | ${cell(t.last_seen)} |`,
  );
  return [head, rule, ...body].join('\n');
}

/** Read the existing registry file, or null when it is absent. Reads directly (no
 *  existsSync precheck) to avoid a check-then-read race; a missing file just yields null. */
function readExisting(abs: string): string | null {
  try {
    return readFileSync(abs, 'utf8');
  } catch {
    return null;
  }
}

/** Pull the hand-authored preamble out of an existing file, or the default when absent. */
function extractPreamble(existing: string | null): string {
  if (existing) {
    const start = existing.indexOf(PREAMBLE_START);
    const end = existing.indexOf(PREAMBLE_END);
    if (start !== -1 && end !== -1 && end > start) {
      return existing.slice(start + PREAMBLE_START.length, end).trim();
    }
  }
  return DEFAULT_PREAMBLE;
}

/** Compose the full registry file content from the preserved preamble + generated table. */
export function composeAnalyticsMap(preamble: string, table: string): string {
  return [
    HEADER,
    '',
    PREAMBLE_START,
    preamble,
    PREAMBLE_END,
    '',
    TABLE_START,
    table,
    TABLE_END,
    '',
  ].join('\n');
}

export interface ReconcileResult {
  path: string;
  content: string;
  tagCount: number;
}

/**
 * Regenerate the tracking map from the ledger, preserving the hand-authored preamble.
 * Writes the file and returns the path + content. Best-effort at the write only — a fold is
 * pure — so a read/parse always succeeds and only the final write can be skipped on fs error.
 */
export function reconcileAnalyticsMap(projectRoot: string): ReconcileResult {
  const abs = join(projectRoot, ANALYTICS_MAP_PATH);
  const existing = readExisting(abs);
  const preamble = extractPreamble(existing);
  const table = renderAnalyticsMapTable(projectRoot);
  const content = composeAnalyticsMap(preamble, table);
  const rows = readAllSessionRows(projectRoot, ANALYTICS_TAG_DOC_TYPE);
  const tagCount = foldAnalyticsTagRows('all', rows).totals.tag_added_count;
  try {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content, 'utf8');
    /* v8 ignore next 3 -- best-effort write; a fs failure is not reproduced in tests */
  } catch {
    // Best-effort: the caller still gets the composed content to surface.
  }
  return { path: ANALYTICS_MAP_PATH, content, tagCount };
}
